### ISSUE TITLE
installation can not complete 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder-Network#17]
Ok , time ago I've opened one issue about ''nothing happens when installation is completed''
Checking the database everything is correct , but installation can not complete , because of the config file .

Installing other script from this project ( encoder , streamer site or storage ) , all of them on the installation process ask you to `chown` the directory . In network-encoder this is missing .

**Fix** for default installation location : `chown -R www-data /var/www/html/AVideo-Encoder-Network`

Hope this could be implemented on the script ( check configuration ) , to avoid this issue . https://github.com/WWBN/AVideo-Encoder-Network/issues/7

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it.

you also can manually check the configuration.php file and give right permission

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I did it like this time before . But that very primitive . 
Most of the user doesn't know what's wrong or what's happening . ( taking example of my self ) , since I was getting no errors , nothing .

Anyway if in the future you have time and want to avoid possible repetitive issues , you can implement it on the script .

You can close the issue ( is not really an issue )

**Comment by DanielnetoDotCom** [comment]
I agree with you.

It will be improved in the future.
