### ISSUE TITLE
No ping or reccommended encoder

### ISSUE THREAD

**Issue by republicus** [WWBN/AVideo-Encoder-Network#2]
Encoder-Network lists all four of my encoders as **online** but makes _no recommendation_ and shows **"Searching Ping ..."**

![network encode](https://user-images.githubusercontent.com/47370709/59153239-da72f980-8a22-11e9-81b8-e4b94084e3bf.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

does your servers answer ping command?

can you manually check it?

**Comment by republicus** [comment]
Well that was easy. I forgot the server was using a FQDN so I opened up ICMP on the firewall to those servers. Pinging is now reporting correctly.

However, I am not sure how to get the ✅ **Recommended** to appear as I see at https://network.youphptube.com/

I have enabled the setting in Admin Panel > Settings> General Settings>
![network-encode-recc](https://user-images.githubusercontent.com/47370709/59200972-65f5a300-8b67-11e9-82b9-0909f8a918eb.PNG)
the link in the picture should work ( https://network.controversreal.com ) if you wish to see it.

Since it says "**(if configured)**", I wonder what configuration might be necessary.

**Comment by DanielnetoDotCom** [comment]
you still can not see the recommended server?

**Comment by republicus** [comment]
Yes that's right.

![network encode 2](https://user-images.githubusercontent.com/47370709/59275160-c51bec00-8c29-11e9-8de2-6a792ed72b9e.PNG)

**Comment by republicus** [comment]
My error logs are filling up. I tried to troubleshoot each error but I'm its not getting anywhere.

### 1. No **cache/score.json** file is being created.

view/score.php is looking for at line 8:
`$file = "{$global['systemRootPath']}cache/score.json";`

That file is never created.

```
ls -l cache/
-rw-r--r-- 1 root     root     194 Jun  8 02:47 index.php
-rw-r--r-- 1 www-data www-data 168 Jun 11 17:48 ping0ca8ff342282abe4dbfcad84df49935d.json
-rw-r--r-- 1 www-data www-data 168 Jun 11 17:48 ping2211b2319f058ecfad705c84d6a3fb7a.json
-rw-r--r-- 1 www-data www-data 167 Jun 11 17:48 ping22832740caf7e3de43a18f2f81a0b49c.json
-rw-r--r-- 1 www-data www-data 156 Jun 11 17:48 ping6a9868b7c86156441864a0f708ddc540.json
-rw-r--r-- 1 www-data www-data 167 Jun 11 17:48 pingcb4663d7458f9de4edea881598715d99.json
```

### 2. SSL and file_get_contents

```
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error [...]
PHP Warning:  file_get_contents(): Failed to enable crypto in [...]
```
For these errors I created the function from [issue #28](https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/28)

```
function getSSLPage($url) {
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_HEADER, false);
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_SSLVERSION,3); 
	$result = curl_exec($ch);
	curl_close($ch);
	return $result;
}
```
I put that function in each location the error above referenced: view/**status.php**, view/**getBestEnoder.php**, view/**index.php**, view/score.php

I compared your resolution since [issue #28](https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/28) and all of the related errors related to _file_get_contents()_ were no longer reported.

### 3. Invalid arguments and non-object errors


`PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/YouPHPTube-Encoder-Network/view/getBestEncoder.php on line 11`

at line 11:   `                  foreach ($encoders as $key => $value) {`

`PHP Notice:  Trying to get property of non-object in /var/www/html/YouPHPTube-Encoder-Network/view/index.php on line 176`

`PHP Notice:  Trying to get property of non-object in /var/www/html/YouPHPTube-Encoder-Network/view/index.php on line 207`

which both reference on index.php: `                            if ($bestEncoder->id == $value['id']) {`

### 4. PING 

Besides whats mentioned above in #3, the apache2 error log is filling quickly with PING results. It claims to be an error but the encoder ping responses are reported properly on the network page (as seen in my previous post).

These must be in error as it claims, though, else i could see the logfile quickly filling and causing problems.

```
[Tue Jun 11 18:26:51.216194 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 3 AND lifetimeSeconds = 5
[Tue Jun 11 18:26:53.759757 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 3 AND lifetimeSeconds = 5
[Tue Jun 11 18:26:53.806001 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 6 AND lifetimeSeconds = 5
[Tue Jun 11 18:26:53.861142 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 6 AND lifetimeSeconds = 5
[Tue Jun 11 18:26:54.014654 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 7 AND lifetimeSeconds = 5
[Tue Jun 11 18:26:54.265688 2019] [:error] [pid 46383] [client 10.7.7.3:46114] PING ==> fileAge = 6 AND lifetimeSeconds = 5
```

**Comment by DanielnetoDotCom** [comment]
Thanks that is a clue

can you delete the cache files on the cache directory?

also check the cache file content.

**Comment by republicus** [comment]
That did nothing to solve the problem. Still the score.json file was never created.
I suspect this may be a php7+ issue (?)

Ive now installed a new VPS from scratch, Centos 7.4 with PHP 5.6
These problems never appeared.

I am willing to do some further testing to verify and help identify any problems.

**Comment by republicus** [comment]
I tried to revisit this and setup a new Network Aggregate.
After a fresh install I was once again getting no pings to encoders and seeing `ping: socket: Operation not permitted` in my apache logs

I attempted:
`chmod 755 $(which ping)`
which did not resolve the problem.

However,  `apt-get reinstall iputils-ping` did work to ping the encoders.

_Still though_, I am getting no recommended encoders.
The encoders show online with ping success as above.

My apache logs show two errors:

`PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/AVideo-Encoder-Network/view/getBestEncoder.php on line 6`

&&

`HP Warning:  Invalid argument supplied for foreach() in /var/www/AVideo-Encoder-Network/view/getBestEncoder.php on line 10`

**Comment by republicus** [comment]
I've now resolved this and will update and close with my remarks.

**Comment by JoshWho** [comment]
U never reported back on what u did.

**Comment by akhilleusuggo** [comment]
@JoshWho maybe you have installed ubuntu-minimal . You need to install `ping ` . It happens to me when installed minimal ubuntu server

**Comment by JoshWho** [comment]
I never had a ping issue, but I do see from time to time the wrong recommendations popping up and hoping there was some kind of relation.

**Comment by republicus** [comment]
My issues were nearly all DNS related after reinstalling ping.
`apt-get reinstall iputils-ping`

I am using reverse proxies to communicate between the network aggregate and each encoder. 
I also run my own bind dns authoritative and caching servers. Once I corrected reverse proxies SSL, hostsnames, and configured DNS and reverse DNS properly they all began working.

@JoshWho Scoring metrics could be looked into.
For example: if an encoder is offline it will be the recommendation.
Ive had encoders with queues that are recommended when many other encoders were online having no queue and equally good ping.

Since my initial issue is resolved as reported and it was all down to my own individual setup and configuration, I'll close this ticket. Thanks for reminding me @JoshWho

**Comment by guymass** [comment]
How do you get your encoders to remain in the Online status? Mine keep constantly switch between online and offline and I have a pretty good ping. I must say though that both my encoders are running behind a reverse proxy tunnel connection, but my ping to the proxy server is under 1sec. Could this effect it? anything I need to check in my configurations or server settings to have a stable online connection to my encoders.

![Screenshot 5784-02-23 at 4 47 03](https://github.com/WWBN/AVideo-Encoder-Network/assets/58882903/1579bbaa-c1e4-41d2-940a-243f35341755)
![Screenshot 5784-02-23 at 4 46 57](https://github.com/WWBN/AVideo-Encoder-Network/assets/58882903/e676eeee-9eed-42a6-8e10-e53818839ea2)
![Screenshot 5784-02-23 at 4 46 43](https://github.com/WWBN/AVideo-Encoder-Network/assets/58882903/dd42a79e-762c-45ec-a0da-13c193d67156)

**Comment by DanielnetoDotCom** [comment]
check your console log.
