### ISSUE TITLE
Play Button image remains visible after clicking play

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo-Encoder-Network#20]
Play button image remains when playing.  Not sure how to fix it.

<img width="968" alt="Screen Shot 2020-05-05 at 10 53 37 PM" src="https://user-images.githubusercontent.com/739391/81135089-c7afc000-8f24-11ea-8996-6d07a811b777.png">

**Comment by DanielnetoDotCom** [comment]
I think this issue has nothing to do with the network.

Please open an new issue on avideo
