### ISSUE TITLE
Reverse Proxy from NGINX to APACHE on HTTPS

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo-Encoder-Network#28]
I have been trying to get a reverse proxy working between nginx and apache.

I have a domain names encoder.ahava528.com, I need to run it along side other sites and while nginx is occupying the ports 80 and 443 I am trying to run the encoder on port 8080 and 8443 respectively.

Is there a proper manual to get this working? I have tried setting this up for quite some time now without success. I had it working on a previous server but the configuration I used there doesn't work for me now. IDK what is going on.

Here are my screenshots for the config files of nginx and apache:
![Screen Shot 5781-06-04 at 17 28 17](https://user-images.githubusercontent.com/58882903/108084144-884dfc80-707c-11eb-8c50-28ab812fb061.jpg)
![Screen Shot 5781-06-04 at 17 28 31](https://user-images.githubusercontent.com/58882903/108084160-8d12b080-707c-11eb-8f97-47d9f00c19e8.jpg)

Would appreciate your help.

**Comment by guymass** [comment]
Also when I try to use only NGINX without apache I get this error message. Is there a way to only use nginx for this script?

![Uploading Screen Shot 5781-06-04 at 17.40.07.jpg…]()

**Comment by akhilleusuggo** [comment]
The latest error is when you're missing the mod_rewrite .

Regarding the vhost conf , you'll probably aldo have to make changes on the apache2 config file. Not sure exactly shere , but youll have to change something else .

If no reverse proxy is presented you will have to include the port number on the url

**Comment by guymass** [comment]
OK I got it working so here are my config files in case anyone is facing the same issues:

apache file:

<VirtualHost *:8080>
    ServerAdmin **YouMail**
    ServerName **YourDomain**
    ServerAlias **YourDomain**
    DocumentRoot /var/www/html/**InstallDirectory**
        <Directory /var/www/html/**InstallDirectory** >
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>


nginx file:

server {
        client_max_body_size 1000M;

        root /var/www/html/**InstallDirectory**;

        index index.php index.html index.htm index.nginx-debian.html;
        server_name **YourDomain**;

        gzip             on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

        location / {

                proxy_pass  http://127.0.0.1:8080;

                ### force timeouts if one of backend is died ##
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

                ### Set headers ####
                proxy_set_header        Accept-Encoding   "";
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

                ### Most PHP, Python, Rails, Java App can use this header ###
                #proxy_set_header X-Forwarded-Proto https;##
                #This is better## 
                proxy_set_header        X-Forwarded-Proto $scheme;
                add_header              Front-End-Https   on;


                ### By default we don't want to redirect it ####
                proxy_redirect     off;

        }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/**YourDomain**/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/**YourDomain**/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = **YourDomain**) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name **YourDomain**;
    listen 80;
    return 404; # managed by Certbot
}
