### ISSUE TITLE
This Streamer site is not allowed

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo-Encoder-Network#30]
I am trying to add an encoder to the Network encoder with no avail. The site is added to the encoders list and approved on each encoder site, but I cannot add it for some reason I keep getting this error message as in the screenshot.

![Screen Shot 5781-06-13 at 13 42 08](https://user-images.githubusercontent.com/58882903/109149276-02af0880-7770-11eb-86fa-66f0e5e9c3a3.jpg)

![Screen Shot 5781-06-12 at 23 43 19](https://user-images.githubusercontent.com/58882903/109149291-093d8000-7770-11eb-932e-7de4e4660cfb.jpg)
![Screen Shot 5781-06-13 at 13 48 20](https://user-images.githubusercontent.com/58882903/109149426-35f19780-7770-11eb-8fb1-d67a01e35334.jpg)
![Screen Shot 5781-06-12 at 23 39 31](https://user-images.githubusercontent.com/58882903/109149717-9ed90f80-7770-11eb-94c5-c8b66343adf1.jpg)

**Comment by DanielnetoDotCom** [comment]
On the encoder try to run this script

https://github.com/WWBN/AVideo-Encoder/blob/master/install/makeEncoderPublic.php

so go to your encoder install dir ...

`cd /var/www/html/EncoderDir/install`

then run the command ...

`php makeEncoderPublic.php`

your encoder should be public now, try again

**Comment by guymass** [comment]
OK I did that but still I cannot see the additional encoder on the list. I also have this error message in Network-Encoder
![Screen Shot 5781-06-13 at 20 35 02](https://user-images.githubusercontent.com/58882903/109200309-1c207680-77a9-11eb-8959-8f7dffef22b3.jpg)

Also on Site General Preferences I have a problem saving the network encoder address. If gives me a this instead:

![Screen Shot 5781-06-13 at 20 36 54](https://user-images.githubusercontent.com/58882903/109200516-63a70280-77a9-11eb-9801-fab50d8ddcea.jpg)

List of encoders show only Live and FETUBE but not EDU

![Screen Shot 5781-06-13 at 20 36 39](https://user-images.githubusercontent.com/58882903/109200551-6e619780-77a9-11eb-9763-877980872856.jpg)

**Comment by DanielnetoDotCom** [comment]
I cannot see any error in your screenshots (the notice is expected)

I am not sure what you are expecting to see

**Comment by guymass** [comment]
im expecting to see my third encoder now under edu.ahava528.com which was the old live. I should have a third option there in the list, I only see two.

**Comment by DanielnetoDotCom** [comment]
But is it on the database?

**Comment by guymass** [comment]
The encoder is listed but now I also see this error message above.

![Screen Shot 5781-06-19 at 13 51 30](https://user-images.githubusercontent.com/58882903/109801786-a0e71680-7c27-11eb-9ff3-18f7f2720fd1.jpg)

**Comment by guymass** [comment]
Another issue I have here is this one, when putting the name of the encoder domain url and than saving, the page refreshes and I get this 1/ appearing instead. Everything is updated, I don't see any errors in logs or browser besides what I have shown.

![Screen Shot 5781-06-19 at 14 26 00](https://user-images.githubusercontent.com/58882903/109805728-7a77aa00-7c2c-11eb-9e26-8ff5291f63aa.jpg)

**Comment by guymass** [comment]
This is my Network encoder configuration.php:

<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'configuration.php'), array('',''), __FILE__);
// Testing here with different webSiteRootURL

$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
//$global['webSiteRootURL'] = 'https://encoder.ahava528.com/';

$global['systemRootPath'] = '/var/www/html/AVideo-Encoder-Network/';


$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'encoder';
$mysqlPass = '';
$mysqlDatabase = '';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
can you please check the apache log file?

there is no reason to not show your encoder if it is on the database.

also try to restart the network server

**Comment by guymass** [comment]
There is nothing in apache or nginx logs regarding the network encoder. I have restarted the apache and the server several times? I cannot see any issues on the network encoder server. Should I check the logs of the encoder itself?

**Comment by DanielnetoDotCom** [comment]
Sorry, then I have no idea what is missing.

**Comment by guymass** [comment]
OK Figured out it was a secondary configuration file that was causing some issues I just didn't noticed before, once I fixed that I was able to add the url properly and now I have them all on the list as it should be.

![Screen Shot 5781-06-21 at 18 33 36](https://user-images.githubusercontent.com/58882903/110161016-71860480-7df5-11eb-870c-ddeece8bcca6.jpg)
