### ISSUE TITLE
Erroring, unable install this when config will not Write

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo-Encoder-Network#33]
I had this running last time and now server / vps refuses write data file, i tried hosting VPS and my personal 1 and getting same on DB and config file. something do with line 29 `$global` functions issues.

**Comment by DanielnetoDotCom** [comment]
All videos folder MUST be writable

**Comment by ChisdealHDYT** [comment]
> All videos folder MUST be writable

so giving hall AVideo Encorder Network Perms 777?

i did that before even give it www-data and it just stuck on loading and loading when pose make config. and when i check logs says about that error and nothing placed in SQL to confirm worked too?

**Comment by ChisdealHDYT** [comment]
this all i get from it even on perms www-data and 777
![image](https://user-images.githubusercontent.com/18028479/127014579-69975a38-b594-4a9c-8b39-ca975182c721.png)
![image](https://user-images.githubusercontent.com/18028479/127014876-ca67599d-ee12-4c6a-ba90-65d6679c79aa.png)

**Comment by DanielnetoDotCom** [comment]
I see, sorry, I confirm there is a bug, try this ...

before you click on the install button create a configuration.php file and make sure it is writable

`cd /var/www/html/AVideo-Encoder-Network &&  touch configuration.php && chmod 777 configuration.php`

**Comment by DanielnetoDotCom** [comment]
I am sending some updates that will make easier the installation.

**Comment by ChisdealHDYT** [comment]
> cd /var/www/html/AVideo-Encoder-Network && touch configuration.php && chmod 777 configuration.php

that didnt fix it? still erroring, its do with `$global` Value issue in `install/index.php`

**Comment by DanielnetoDotCom** [comment]
you probably will need to drop the database and then update the encoder network

then try to run the installation again

**Comment by DanielnetoDotCom** [comment]
Just sent you a couple new updates

**Comment by ChisdealHDYT** [comment]
> Just sent you a couple new updates

still getting `Undefined variable: global in /var/www/AVideo-Encoder-Network/install/index.php on line 28\n'`, i told you exact issue? its Installer not DB because DB is empty

**Comment by ChisdealHDYT** [comment]
as see
![image](https://user-images.githubusercontent.com/18028479/127024419-3b01f3c0-ee27-44d8-8c21-050168308099.png)

**Comment by DanielnetoDotCom** [comment]
> > Just sent you a couple new updates
> 
> still getting `Undefined variable: global in /var/www/AVideo-Encoder-Network/install/index.php on line 28\n'`, i told you exact issue? its Installer not DB because DB is empty

Nothing to worry about this warning

**Comment by Waffleuncle** [comment]
![image](https://user-images.githubusercontent.com/76669896/128199189-8efe828c-de88-474d-ad05-347791ca11c3.png)
we have now this prob but every thing is 777 on chmod

**Comment by DanielnetoDotCom** [comment]
did you manually create the configuration.php file?

**Comment by Waffleuncle** [comment]
Not at all

**Comment by dedisoft** [comment]
Hi,

Sorry, I've the same issue and i've created the configuration.php file with good rights.

I see on error log this just before " must be writable":

[15-Sep-2021 14:13:40 UTC] PHP Notice:  Undefined variable: configFile in /xxx/install/checkConfiguration.php on line 19
[15-Sep-2021 14:13:40 UTC] PHP Notice:  Undefined variable: configFile in /xxx/install/checkConfiguration.php on line 20

Thanks

**Comment by Fre68** [comment]
Hello, I installed your script for Christian videos.
Everything was fine, maintaining the encoder no longer works. Can not access the page to encode.
Frédéric

**Comment by DanielnetoDotCom** [comment]
what exactly encoder are you referring to?

**Comment by Fre68** [comment]
I was able to place 15 videos with:
https://encoder2.avideo.com/
and
  https://encoder1.avideo.com/
And since then, nothing

**Comment by DanielnetoDotCom** [comment]
We had a DNS problem today . The encoders should be good now

**Comment by Fre68** [comment]
Hello and thank you for answering me

It is 10 hours in France, and when I click on "Uploading a new media", I arrive on a blank page: address not found.

**Comment by DanielnetoDotCom** [comment]
Sorry for the inconvenience, we still trying to resolve the Cloudflare issue.

**Comment by DanielnetoDotCom** [comment]
Sorry, what option do you want to remove?

**Comment by Fre68** [comment]
Automatic reading, everywhere

**Comment by Fre68** [comment]
A video that starts alone

**Comment by Fre68** [comment]
hello I come back to you because I really have a problem with the "automatic reading"

I configured correctly

When I integrate a video on my site, it starts automatically, which is very part of
Look here, in drawing of the article! 

https://bible-foi.com/gabelle-frederic/655-actualisation-des-objectifs-de-bible-foi-com#presentation-de-la-plateforme-bible-ouverte-fr

**Comment by DanielnetoDotCom** [comment]
For me it did not start automatically

<img width="774" alt="image" src="https://user-images.githubusercontent.com/18009293/160124983-37497b42-6a6e-42b1-85f6-99a05b0ed36d.png">


you are using this URL  in your iframe

https://www.bible-ouverte.fr/videoEmbed/55/presentation-de-la-plateforme-bible-ouverte.fr-.?channelName=Acoeurouvert&modestbranding=1&showinfo=1&autoplay=&controls=1&loop=&mute=&t=0&objectFit=

try to add the autoplay=0, so youe URL will be 

https://www.bible-ouverte.fr/videoEmbed/55/presentation-de-la-plateforme-bible-ouverte.fr-.?channelName=Acoeurouvert&modestbranding=1&showinfo=1&autoplay=0&controls=1&loop=&mute=&t=0&objectFit=

**Comment by Fre68** [comment]
try
https://bible-foi.com/gabelle-frederic/655-actualisation-des-objectifs-de-bible-foi-com

Click on the page outside the video 
![Uploading Sans titre 1.jpg…]()

**Comment by DanielnetoDotCom** [comment]
Not autoplaying

![image](https://user-images.githubusercontent.com/18009293/160173028-0d9f2be7-c059-4dd2-9588-a53239cf43d3.png)

Try from an incognito browser or clear your browser cookies

Probably the autoplay cookie is on your browser

**Comment by Fre68** [comment]
ok I'll see

**Comment by ChisdealHDYT** [comment]
sorry for most of you here, i have to close this since i was getting too many emails and this was pose do with config issue not encorder issue.

make sure make new issue, since trying prevent email spams on here.

Thank you :)
