### ISSUE TITLE
Network encoder file_get_contents(): SSL operation failed with code 1.

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo-Encoder-Network#36]
Network encoder file_get_contents(): SSL operation failed with code 1.
![image](https://user-images.githubusercontent.com/47063171/135832506-19e247c2-6a7d-4700-9c96-515798bee99d.png)

**Comment by DanielnetoDotCom** [comment]
Hi, please try this update

**Comment by chenjian9885** [comment]
OK
