### ISSUE TITLE
Encoder Network - Streamers Table - Password Field

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo-Encoder-Network#37]
Can't login to Encoder Network from AVideo. Modified `pass` field to varchar(255) same as Encoder. As an aside, AVideo `password` field in Users table is varchar(145), seems logical they all should match. Copied Admin password from Encoder and updated Encoder Network to reflect same. Was able to login from AVideo. This all happened on fresh installation of Encoder Network.

**Comment by GreenDragonTavern** [comment]
Commented on another post regarding Encoder Network login failure. Did exactly as you mentioned, pulled down all plugins and fresh on AVideo, Encoder, Encoder-Network. Only when I modified pass field structure to varchar(255) in streamers table on Encoder-Network database was I able to login.

**Comment by DanielnetoDotCom** [comment]
Humm, I see.

you may be right, I guess I missed that.

thanks, that helps a lot.
I will build something to update it
